// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/query.proto

package queryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetStatsRequest specifies time range for statistics
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Optional: if not set, includes all time from beginning
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // Optional: if not set, includes up to current time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetStatsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// GetStatsResponse contains aggregated statistics
type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// GetAPIRequestsRequest specifies filters for API requests
type GetAPIRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Optional: if not set, includes all time from beginning
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // Optional: if not set, includes up to current time
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                         // Optional limit for number of results
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                       // Optional offset for pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAPIRequestsRequest) Reset() {
	*x = GetAPIRequestsRequest{}
	mi := &file_proto_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAPIRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPIRequestsRequest) ProtoMessage() {}

func (x *GetAPIRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPIRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetAPIRequestsRequest) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{2}
}

func (x *GetAPIRequestsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetAPIRequestsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetAPIRequestsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAPIRequestsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// GetAPIRequestsResponse contains API request records
type GetAPIRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*APIRequest          `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total count without pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAPIRequestsResponse) Reset() {
	*x = GetAPIRequestsResponse{}
	mi := &file_proto_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAPIRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPIRequestsResponse) ProtoMessage() {}

func (x *GetAPIRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPIRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetAPIRequestsResponse) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{3}
}

func (x *GetAPIRequestsResponse) GetRequests() []*APIRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *GetAPIRequestsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Stats represents aggregated statistics
type Stats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BaseRequests    int32                  `protobuf:"varint,1,opt,name=base_requests,json=baseRequests,proto3" json:"base_requests,omitempty"`
	PremiumRequests int32                  `protobuf:"varint,2,opt,name=premium_requests,json=premiumRequests,proto3" json:"premium_requests,omitempty"`
	TotalRequests   int32                  `protobuf:"varint,3,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	BaseTokens      *Token                 `protobuf:"bytes,4,opt,name=base_tokens,json=baseTokens,proto3" json:"base_tokens,omitempty"`
	PremiumTokens   *Token                 `protobuf:"bytes,5,opt,name=premium_tokens,json=premiumTokens,proto3" json:"premium_tokens,omitempty"`
	TotalTokens     *Token                 `protobuf:"bytes,6,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	BaseCost        *Cost                  `protobuf:"bytes,7,opt,name=base_cost,json=baseCost,proto3" json:"base_cost,omitempty"`
	PremiumCost     *Cost                  `protobuf:"bytes,8,opt,name=premium_cost,json=premiumCost,proto3" json:"premium_cost,omitempty"`
	TotalCost       *Cost                  `protobuf:"bytes,9,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_proto_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{4}
}

func (x *Stats) GetBaseRequests() int32 {
	if x != nil {
		return x.BaseRequests
	}
	return 0
}

func (x *Stats) GetPremiumRequests() int32 {
	if x != nil {
		return x.PremiumRequests
	}
	return 0
}

func (x *Stats) GetTotalRequests() int32 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *Stats) GetBaseTokens() *Token {
	if x != nil {
		return x.BaseTokens
	}
	return nil
}

func (x *Stats) GetPremiumTokens() *Token {
	if x != nil {
		return x.PremiumTokens
	}
	return nil
}

func (x *Stats) GetTotalTokens() *Token {
	if x != nil {
		return x.TotalTokens
	}
	return nil
}

func (x *Stats) GetBaseCost() *Cost {
	if x != nil {
		return x.BaseCost
	}
	return nil
}

func (x *Stats) GetPremiumCost() *Cost {
	if x != nil {
		return x.PremiumCost
	}
	return nil
}

func (x *Stats) GetTotalCost() *Cost {
	if x != nil {
		return x.TotalCost
	}
	return nil
}

// Token represents token usage statistics
type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Input         int64                  `protobuf:"varint,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        int64                  `protobuf:"varint,3,opt,name=output,proto3" json:"output,omitempty"`
	CacheRead     int64                  `protobuf:"varint,4,opt,name=cache_read,json=cacheRead,proto3" json:"cache_read,omitempty"`
	CacheCreation int64                  `protobuf:"varint,5,opt,name=cache_creation,json=cacheCreation,proto3" json:"cache_creation,omitempty"`
	Limited       int64                  `protobuf:"varint,6,opt,name=limited,proto3" json:"limited,omitempty"`
	Cache         int64                  `protobuf:"varint,7,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_proto_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{5}
}

func (x *Token) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Token) GetInput() int64 {
	if x != nil {
		return x.Input
	}
	return 0
}

func (x *Token) GetOutput() int64 {
	if x != nil {
		return x.Output
	}
	return 0
}

func (x *Token) GetCacheRead() int64 {
	if x != nil {
		return x.CacheRead
	}
	return 0
}

func (x *Token) GetCacheCreation() int64 {
	if x != nil {
		return x.CacheCreation
	}
	return 0
}

func (x *Token) GetLimited() int64 {
	if x != nil {
		return x.Limited
	}
	return 0
}

func (x *Token) GetCache() int64 {
	if x != nil {
		return x.Cache
	}
	return 0
}

// Cost represents cost information
type Cost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cost) Reset() {
	*x = Cost{}
	mi := &file_proto_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cost) ProtoMessage() {}

func (x *Cost) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cost.ProtoReflect.Descriptor instead.
func (*Cost) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{6}
}

func (x *Cost) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// APIRequest represents a single API request record
type APIRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SessionId           string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Model               string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	InputTokens         int64                  `protobuf:"varint,4,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens        int64                  `protobuf:"varint,5,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheReadTokens     int64                  `protobuf:"varint,6,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	CacheCreationTokens int64                  `protobuf:"varint,7,opt,name=cache_creation_tokens,json=cacheCreationTokens,proto3" json:"cache_creation_tokens,omitempty"`
	TotalTokens         int64                  `protobuf:"varint,8,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	CostUsd             float64                `protobuf:"fixed64,9,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	DurationMs          int64                  `protobuf:"varint,10,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *APIRequest) Reset() {
	*x = APIRequest{}
	mi := &file_proto_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest) ProtoMessage() {}

func (x *APIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest.ProtoReflect.Descriptor instead.
func (*APIRequest) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{7}
}

func (x *APIRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *APIRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *APIRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *APIRequest) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *APIRequest) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *APIRequest) GetCacheReadTokens() int64 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *APIRequest) GetCacheCreationTokens() int64 {
	if x != nil {
		return x.CacheCreationTokens
	}
	return 0
}

func (x *APIRequest) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *APIRequest) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *APIRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_proto_query_proto protoreflect.FileDescriptor

const file_proto_query_proto_rawDesc = "" +
	"\n" +
	"\x11proto/query.proto\x12\bccmon.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n" +
	"\x0fGetStatsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"9\n" +
	"\x10GetStatsResponse\x12%\n" +
	"\x05stats\x18\x01 \x01(\v2\x0f.ccmon.v1.StatsR\x05stats\"\xb7\x01\n" +
	"\x15GetAPIRequestsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"k\n" +
	"\x16GetAPIRequestsResponse\x120\n" +
	"\brequests\x18\x01 \x03(\v2\x14.ccmon.v1.APIRequestR\brequests\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xab\x03\n" +
	"\x05Stats\x12#\n" +
	"\rbase_requests\x18\x01 \x01(\x05R\fbaseRequests\x12)\n" +
	"\x10premium_requests\x18\x02 \x01(\x05R\x0fpremiumRequests\x12%\n" +
	"\x0etotal_requests\x18\x03 \x01(\x05R\rtotalRequests\x120\n" +
	"\vbase_tokens\x18\x04 \x01(\v2\x0f.ccmon.v1.TokenR\n" +
	"baseTokens\x126\n" +
	"\x0epremium_tokens\x18\x05 \x01(\v2\x0f.ccmon.v1.TokenR\rpremiumTokens\x122\n" +
	"\ftotal_tokens\x18\x06 \x01(\v2\x0f.ccmon.v1.TokenR\vtotalTokens\x12+\n" +
	"\tbase_cost\x18\a \x01(\v2\x0e.ccmon.v1.CostR\bbaseCost\x121\n" +
	"\fpremium_cost\x18\b \x01(\v2\x0e.ccmon.v1.CostR\vpremiumCost\x12-\n" +
	"\n" +
	"total_cost\x18\t \x01(\v2\x0e.ccmon.v1.CostR\ttotalCost\"\xc1\x01\n" +
	"\x05Token\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x14\n" +
	"\x05input\x18\x02 \x01(\x03R\x05input\x12\x16\n" +
	"\x06output\x18\x03 \x01(\x03R\x06output\x12\x1d\n" +
	"\n" +
	"cache_read\x18\x04 \x01(\x03R\tcacheRead\x12%\n" +
	"\x0ecache_creation\x18\x05 \x01(\x03R\rcacheCreation\x12\x18\n" +
	"\alimited\x18\x06 \x01(\x03R\alimited\x12\x14\n" +
	"\x05cache\x18\a \x01(\x03R\x05cache\"\x1e\n" +
	"\x04Cost\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\"\x82\x03\n" +
	"\n" +
	"APIRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12!\n" +
	"\finput_tokens\x18\x04 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x05 \x01(\x03R\foutputTokens\x12*\n" +
	"\x11cache_read_tokens\x18\x06 \x01(\x03R\x0fcacheReadTokens\x122\n" +
	"\x15cache_creation_tokens\x18\a \x01(\x03R\x13cacheCreationTokens\x12!\n" +
	"\ftotal_tokens\x18\b \x01(\x03R\vtotalTokens\x12\x19\n" +
	"\bcost_usd\x18\t \x01(\x01R\acostUsd\x12\x1f\n" +
	"\vduration_ms\x18\n" +
	" \x01(\x03R\n" +
	"durationMs2\xa6\x01\n" +
	"\fQueryService\x12A\n" +
	"\bGetStats\x12\x19.ccmon.v1.GetStatsRequest\x1a\x1a.ccmon.v1.GetStatsResponse\x12S\n" +
	"\x0eGetAPIRequests\x12\x1f.ccmon.v1.GetAPIRequestsRequest\x1a .ccmon.v1.GetAPIRequestsResponseB)Z'github.com/elct9620/ccmon/proto/queryv1b\x06proto3"

var (
	file_proto_query_proto_rawDescOnce sync.Once
	file_proto_query_proto_rawDescData []byte
)

func file_proto_query_proto_rawDescGZIP() []byte {
	file_proto_query_proto_rawDescOnce.Do(func() {
		file_proto_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_query_proto_rawDesc), len(file_proto_query_proto_rawDesc)))
	})
	return file_proto_query_proto_rawDescData
}

var file_proto_query_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_query_proto_goTypes = []any{
	(*GetStatsRequest)(nil),        // 0: ccmon.v1.GetStatsRequest
	(*GetStatsResponse)(nil),       // 1: ccmon.v1.GetStatsResponse
	(*GetAPIRequestsRequest)(nil),  // 2: ccmon.v1.GetAPIRequestsRequest
	(*GetAPIRequestsResponse)(nil), // 3: ccmon.v1.GetAPIRequestsResponse
	(*Stats)(nil),                  // 4: ccmon.v1.Stats
	(*Token)(nil),                  // 5: ccmon.v1.Token
	(*Cost)(nil),                   // 6: ccmon.v1.Cost
	(*APIRequest)(nil),             // 7: ccmon.v1.APIRequest
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_proto_query_proto_depIdxs = []int32{
	8,  // 0: ccmon.v1.GetStatsRequest.start_time:type_name -> google.protobuf.Timestamp
	8,  // 1: ccmon.v1.GetStatsRequest.end_time:type_name -> google.protobuf.Timestamp
	4,  // 2: ccmon.v1.GetStatsResponse.stats:type_name -> ccmon.v1.Stats
	8,  // 3: ccmon.v1.GetAPIRequestsRequest.start_time:type_name -> google.protobuf.Timestamp
	8,  // 4: ccmon.v1.GetAPIRequestsRequest.end_time:type_name -> google.protobuf.Timestamp
	7,  // 5: ccmon.v1.GetAPIRequestsResponse.requests:type_name -> ccmon.v1.APIRequest
	5,  // 6: ccmon.v1.Stats.base_tokens:type_name -> ccmon.v1.Token
	5,  // 7: ccmon.v1.Stats.premium_tokens:type_name -> ccmon.v1.Token
	5,  // 8: ccmon.v1.Stats.total_tokens:type_name -> ccmon.v1.Token
	6,  // 9: ccmon.v1.Stats.base_cost:type_name -> ccmon.v1.Cost
	6,  // 10: ccmon.v1.Stats.premium_cost:type_name -> ccmon.v1.Cost
	6,  // 11: ccmon.v1.Stats.total_cost:type_name -> ccmon.v1.Cost
	8,  // 12: ccmon.v1.APIRequest.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 13: ccmon.v1.QueryService.GetStats:input_type -> ccmon.v1.GetStatsRequest
	2,  // 14: ccmon.v1.QueryService.GetAPIRequests:input_type -> ccmon.v1.GetAPIRequestsRequest
	1,  // 15: ccmon.v1.QueryService.GetStats:output_type -> ccmon.v1.GetStatsResponse
	3,  // 16: ccmon.v1.QueryService.GetAPIRequests:output_type -> ccmon.v1.GetAPIRequestsResponse
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_query_proto_init() }
func file_proto_query_proto_init() {
	if File_proto_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_query_proto_rawDesc), len(file_proto_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_query_proto_goTypes,
		DependencyIndexes: file_proto_query_proto_depIdxs,
		MessageInfos:      file_proto_query_proto_msgTypes,
	}.Build()
	File_proto_query_proto = out.File
	file_proto_query_proto_goTypes = nil
	file_proto_query_proto_depIdxs = nil
}
